[tox]
envlist =
        py{312,313,314}-django{52,60},
        flake8,
        docs
skipsdist = True


[gh-actions]
python =
  3.12: py312-django52, py312-django60
  3.13: py312-django60, flake8, docs
  3.14: py312-django60


[testenv]
changedir = test_project
commands =
        python -Wd manage.py test front

setenv =
        PYTHONDONTWRITEBYTECODE=1

deps =
       django52: Django>=5.2.8,<5.3
       django60: Django>=6.0,<6.1
       pymemcache
       coverage
       django-classy-tags
       south
       django-wymeditor
       six

[testenv:flake8]
basepython = python3
deps = flake8
commands=
    flake8 {toxinidir}/front

[testenv:docs]
deps =
        sphinx
        sphinx-book-theme

changedir = docs
commands=
        sphinx-build -W -b html . _build/html


[flake8]
ignore = E501,W503
