name: Test Django Front

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v5
     - name: Install uv
       uses: astral-sh/setup-uv
     - uses: niden/actions-memcached@v8
     - name: Install tox-uv
       run: uv tool install tox --with tox-uv
     - name: Test with tox
       run: tox
